import { notFound } from "next/navigation";
import { AdminActionForm, type ActionState } from "@/components/admin/action-form";
import { deleteResourceAction, saveResourceAction } from "@/features/admin/actions";
import { adminResourceSchema, type AdminResource } from "@/features/admin/schemas";
import { prisma } from "@/lib/prisma";

type Search = Promise<{ q?: string | string[] }>;
type Action = (state: ActionState, formData: FormData) => Promise<ActionState>;
const textInput = "mt-1 w-full border border-line bg-background px-3 py-2 text-sm text-white";

function Field({ name, label, value = "", type = "text", required = false }: { name: string; label: string; value?: string | number | null; type?: string; required?: boolean }) { return <label className="block text-sm text-muted">{label}<input name={name} type={type} defaultValue={value ?? ""} required={required} className={textInput} /></label>; }
function Select({ name, label, value, options }: { name: string; label: string; value?: string | null; options: { id: string; label: string }[] }) { return <label className="block text-sm text-muted">{label}<select name={name} defaultValue={value ?? ""} className={textInput}><option value="">Select…</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>; }
function Enum({ name, label, value, options }: { name: string; label: string; value?: string | null; options: string[] }) { return <label className="block text-sm text-muted">{label}<select name={name} defaultValue={value ?? options[0]} className={textInput}>{options.map((option) => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select></label>; }

function ResourceFields({ resource, record, manufacturers, models, generations, vehicles, sources }: { resource: AdminResource; record?: Record<string, unknown>; manufacturers: { id: string; label: string }[]; models: { id: string; label: string }[]; generations: { id: string; label: string }[]; vehicles: { id: string; label: string }[]; sources: { id: string; label: string }[] }) {
  if (resource === "manufacturers") return <><Field name="name" label="Name" value={record?.name as string} required /><Field name="slug" label="Slug" value={record?.slug as string} required /><Field name="country" label="Country" value={record?.country as string} /><Field name="foundedIn" label="Founded" type="number" value={record?.foundedIn as number} /></>;
  if (resource === "models") return <><Select name="manufacturerId" label="Manufacturer" value={record?.manufacturerId as string} options={manufacturers} /><Field name="name" label="Name" value={record?.name as string} required /><Field name="slug" label="Slug" value={record?.slug as string} required /></>;
  if (resource === "generations") return <><Select name="modelId" label="Model" value={record?.modelId as string} options={models} /><Field name="code" label="Generation code" value={record?.code as string} required /><Field name="displayName" label="Display name" value={record?.displayName as string} /><Field name="startYear" label="Start year" type="number" value={record?.startYear as number} /><Field name="endYear" label="End year" type="number" value={record?.endYear as number} /></>;
  if (resource === "model-years") return <><Select name="generationId" label="Generation" value={record?.generationId as string} options={generations} /><Field name="year" label="Year" type="number" value={record?.year as number} required /></>;
  if (resource === "engines") return <><Select name="manufacturerId" label="Manufacturer (optional)" value={record?.manufacturerId as string} options={manufacturers} /><Field name="name" label="Engine name" value={record?.name as string} required /><Field name="slug" label="Slug" value={record?.slug as string} required /><Field name="code" label="Code" value={record?.code as string} /><Enum name="fuelType" label="Fuel type" value={record?.fuelType as string} options={["PETROL", "DIESEL", "HYBRID", "PLUG_IN_HYBRID", "ELECTRIC", "HYDROGEN", "FLEX_FUEL"]} /><Field name="displacementCc" label="Displacement (cc)" type="number" value={record?.displacementCc as number} /><Field name="cylinderCount" label="Cylinders" type="number" value={record?.cylinderCount as number} /><Field name="configuration" label="Configuration" value={record?.configuration as string} /><Field name="induction" label="Induction" value={record?.induction as string} /><Field name="electrification" label="Electrification" value={record?.electrification as string} /></>;
  if (resource === "transmissions") return <><Field name="name" label="Name" value={record?.name as string} required /><Field name="slug" label="Slug" value={record?.slug as string} required /><Enum name="type" label="Type" value={record?.type as string} options={["AUTOMATIC", "CVT", "DUAL_CLUTCH", "MANUAL", "SINGLE_SPEED"]} /><Field name="gearCount" label="Gear count" type="number" value={record?.gearCount as number} /></>;
  if (resource === "sources") return <><Field name="title" label="Title" value={record?.title as string} required /><Field name="slug" label="Slug" value={record?.slug as string} required /><Field name="publisher" label="Publisher" value={record?.publisher as string} required /><Field name="url" label="URL" type="url" value={record?.url as string} required /><Enum name="type" label="Source type" value={record?.type as string} options={["MANUFACTURER", "GOVERNMENT", "PRESS_RELEASE", "OWNER_MANUAL", "THIRD_PARTY"]} /><Field name="publishedAt" label="Published date" type="date" value={record?.publishedAt ? new Date(record.publishedAt as string).toISOString().slice(0, 10) : ""} /></>;
  return <><Select name="vehicleId" label="Trim" value={record?.vehicleId as string} options={vehicles} /><Select name="sourceId" label="Source (optional)" value={record?.sourceId as string} options={sources} /><Field name="url" label="Image URL" type="url" value={record?.url as string} required /><Field name="alt" label="Alt text" value={record?.alt as string} required /><Field name="credit" label="Credit" value={record?.credit as string} /><Field name="position" label="Position" type="number" value={record?.position as number ?? 0} required /></>;
}

export default async function ResourcePage({ params, searchParams }: { params: Promise<{ resource: string }>; searchParams: Search }) {
  const { resource: resourceValue } = await params; const resource = adminResourceSchema.safeParse(resourceValue); if (!resource.success) notFound(); const q = typeof (await searchParams).q === "string" ? (await searchParams).q as string : "";
  const [manufacturers, models, generations, vehicles, sources] = await Promise.all([prisma.manufacturer.findMany({ select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.vehicleModel.findMany({ include: { manufacturer: true }, orderBy: { name: "asc" } }), prisma.vehicleGeneration.findMany({ include: { model: { include: { manufacturer: true } } }, orderBy: { code: "asc" } }), prisma.vehicle.findMany({ include: { modelYear: { include: { generation: { include: { model: { include: { manufacturer: true } } } } } } }, take: 100, orderBy: { updatedAt: "desc" } }), prisma.source.findMany({ select: { id: true, title: true }, orderBy: { title: "asc" } })]);
  const options = { manufacturers: manufacturers.map((x) => ({ id: x.id, label: x.name })), models: models.map((x) => ({ id: x.id, label: `${x.manufacturer.name} ${x.name}` })), generations: generations.map((x) => ({ id: x.id, label: `${x.model.manufacturer.name} ${x.model.name} ${x.code}` })), vehicles: vehicles.map((x) => ({ id: x.id, label: `${x.modelYear.year} ${x.modelYear.generation.model.manufacturer.name} ${x.modelYear.generation.model.name} ${x.name}` })), sources: sources.map((x) => ({ id: x.id, label: x.title })) };
  let records: Record<string, unknown>[] = [];
  if (resource.data === "manufacturers") records = await prisma.manufacturer.findMany({ where: q ? { name: { contains: q, mode: "insensitive" } } : {}, take: 50, orderBy: { name: "asc" } });
  if (resource.data === "models") records = await prisma.vehicleModel.findMany({ where: q ? { name: { contains: q, mode: "insensitive" } } : {}, take: 50, orderBy: { name: "asc" } });
  if (resource.data === "generations") records = await prisma.vehicleGeneration.findMany({ where: q ? { code: { contains: q, mode: "insensitive" } } : {}, take: 50, orderBy: { code: "asc" } });
  if (resource.data === "model-years") records = await prisma.modelYear.findMany({ where: q && /^\d+$/.test(q) ? { year: Number(q) } : {}, take: 50, orderBy: { year: "desc" } });
  if (resource.data === "engines") records = await prisma.engine.findMany({ where: q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { code: { contains: q, mode: "insensitive" } }] } : {}, take: 50, orderBy: { name: "asc" } });
  if (resource.data === "transmissions") records = await prisma.transmission.findMany({ where: q ? { name: { contains: q, mode: "insensitive" } } : {}, take: 50, orderBy: { name: "asc" } });
  if (resource.data === "sources") records = await prisma.source.findMany({ where: q ? { OR: [{ title: { contains: q, mode: "insensitive" } }, { publisher: { contains: q, mode: "insensitive" } }] } : {}, take: 50, orderBy: { updatedAt: "desc" } });
  if (resource.data === "images") records = await prisma.vehicleImage.findMany({ where: q ? { alt: { contains: q, mode: "insensitive" } } : {}, take: 50, orderBy: { createdAt: "desc" } });
  const save = saveResourceAction.bind(null, resource.data, undefined) as Action;
  return <main><p className="font-mono text-[0.65rem] tracking-[0.16em] text-signal uppercase">Catalogue data</p><h1 className="mt-3 text-4xl font-semibold capitalize text-white">{resource.data.replaceAll("-", " ")}</h1><form className="mt-6"><input name="q" defaultValue={q} placeholder="Search this list" className={textInput} /></form><details className="mt-6 border border-line bg-background p-5"><summary className="cursor-pointer font-mono text-xs tracking-[0.12em] text-white uppercase">Create {resource.data.slice(0, -1).replaceAll("-", " ")}</summary><AdminActionForm action={save} className="mt-5 grid gap-4 sm:grid-cols-2"><ResourceFields resource={resource.data} {...options} /></AdminActionForm></details><div className="mt-6 grid gap-3">{records.map((record) => { const id = record.id as string; const label = String(record.name ?? record.title ?? record.code ?? record.year ?? record.alt ?? id); const update = saveResourceAction.bind(null, resource.data, id) as Action; const remove = deleteResourceAction.bind(null, resource.data, id) as Action; return <details key={id} className="border border-line bg-background p-4"><summary className="cursor-pointer text-white">{label}</summary><AdminActionForm action={update} className="mt-5 grid gap-4 sm:grid-cols-2"><ResourceFields resource={resource.data} record={record} {...options} /></AdminActionForm><AdminActionForm action={remove} className="mt-5 border-t border-line pt-4"><label className="flex items-center gap-2 text-sm text-muted"><input name="confirm" type="checkbox" /> I understand this deletion is permanent.</label></AdminActionForm></details>; })}</div>{records.length === 50 ? <p className="mt-5 text-sm text-muted">Showing the first 50 matching records. Refine your search for more.</p> : null}</main>;
}
